server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,prometheus}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:always}

logging:
  level:
    com.taskflow: ${LOG_LEVEL_APP:DEBUG}
