{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.services.apiGateway.port }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.services.apiGateway.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.services.frontend.port }}
{{- end }}
