apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.notificationService }}
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" (dict "app" "notification-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels" (dict "app" "notification-service") | nindent 8 }}
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.images.notificationService }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.notificationService.port }}
          env:
            # RabbitMQ
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: RABBITMQ_PASSWORD
          resources:
            {{- toYaml .Values.resources.notificationService | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.notificationService.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.notificationService.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskflow.selectorLabels" (dict "app" "notification-service") | nindent 4 }}
  ports:
    - port: {{ .Values.services.notificationService.port }}
      targetPort: {{ .Values.services.notificationService.port }}
  type: ClusterIP
