apiVersion: v1
kind: Service
metadata:
  name: postgres-task
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-task
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: postgres-task
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-task
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-task
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  serviceName: postgres-task
  replicas: 1
  selector:
    matchLabels:
      app: postgres-task
  template:
    metadata:
      labels:
        app: postgres-task
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.taskDb.name | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-task-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              {{- toYaml .Values.resources.postgres.requests | nindent 14 }}
            limits:
              {{- toYaml .Values.resources.postgres.limits | nindent 14 }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-task-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.resources.postgres.storageSize }}
