apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taskflow.selectorLabels" (dict "app" "rabbitmq") | nindent 4 }}
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" (dict "app" "rabbitmq") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels" (dict "app" "rabbitmq") | nindent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: RABBITMQ_PASSWORD
          resources:
            {{- toYaml .Values.resources.rabbitmq | nindent 12 }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
