apiVersion: v1
kind: Service
metadata:
  name: postgres-task
  namespace: taskflow
  labels:
    app: postgres-task
    app.kubernetes.io/part-of: taskflow
spec:
  clusterIP: None
  selector:
    app: postgres-task
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-task
  namespace: taskflow
  labels:
    app: postgres-task
    app.kubernetes.io/part-of: taskflow
spec:
  serviceName: postgres-task
  replicas: 1
  selector:
    matchLabels:
      app: postgres-task
  template:
    metadata:
      labels:
        app: postgres-task
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "taskflow_tasks"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-task-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-task-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
