apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: taskflow
  labels:
    app: user-service
    app.kubernetes.io/part-of: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: taskflow/user-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: USER_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: USER_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: USER_DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DB_PASSWORD
            # JWT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: JWT_EXPIRATION
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: taskflow
  labels:
    app: user-service
    app.kubernetes.io/part-of: taskflow
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
